### PR TITLE
Add maximum missed cleavage parameter

### PR DESCRIPTION
**Pull request by CWRU-CPB**
I am proposing a solution for restricting candidate peptides to a maximum number of missed cleavages (this has a "help wanted" tag under issues). I am not sure how much detail to put in the initial pull request, but the following summarizes what was done and what steps have been taken to validate the results.

The proposed changes alter the CandidatePeptideGrid so that it will refuse to generate peptides that violate the maximum number of missed cleavages. The proposed approach should work for ntt=0/1/2. SearchParams reports an error if unspecific or no-cleavage enzymes are being used because, while the method can handle them, I couldn't think of a valid reason to use a max missed cleavages value with either of those enzymes. A default value -1=="unlimited" has been set so that not specifying a value for the parameter should generate results that match the current stable release.

I have added JUnit tests to perform automated checks for expected behavior of CandidatePepetideGrid* classes with the proposed changes that test C-term, N-term, unspecific and no-cleave enzymes and have also done the following tests with real data and Trypsin to check for inconsistencies:

1) Compared the result peptides from the current stable release against the proposed modified version when specifying unlimited missed cleavages to verify default behavior is backward compatible.

2) Compared the result peptides from the current stable release against the proposed modified version when specifying 1 missed cleavage to verify that peptide results unique to the current stable release have more than 1 missed cleavage.

I'm sure we will have to discuss this prior to accepting. Thanks.

### CODE REVIEW

**Comment by FarmGeek4Life** [comment]
Just a comment on style: I would ask that the trailing whitespace be removed (there appears to be a large number of these), and there are a couple instances where an existing blank line was removed that should have been kept (CandidatePeptideGrid L107 and L214). Sometime I need to get a style preferences/guide up; but I didn't see anything else, beyond a preference for '//' for single line comments (but not asking you to change that).

**Comment by CWRU-CPB** [comment]
I used a regex to remove what I think you were referring to as trailing white space and the diff to upstream master looks much cleaner. I also changed the range of the allowed values to include 0 and added a test to verify it (I don't know why I initially restricted it, because 0 is a valid and useful value for it)

**Comment by CWRU-CPB** [comment]
I have a git config issue here that resulted in not associating my commits to my account. Do you mind if I close this pull request and re-open it so things are properly attributed?

**Comment by CWRU-CPB** [comment]
I'm going to start over. Will submit another pull request with a clean checkout of master and a new branch.

**Pull request closed without merging**
